[package]
name = "lifx"
version = "0.0.1-pre"
authors = [ "Bo Jeanes <me@bjeanes.com>" ]
description = "Library to control and inspect LIFX bulbs"
repository = "https://github.com/bjeanes/lifx-rust"
license = "MPL-2.0"

